spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5433/shoppingdb
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl:auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0