server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/shoppingdb
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl:auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-02009464.okta.com/oauth2/default
      client:
        registration:
          okta:
            provider: okta
            authorization-grant-type: client_credentials
            scope: app_scope
            client-id: 0oa9nah80n4ds7NZ85d7
            client-secret: SsaufzfudAFduzPx6S-fK5d9EAz-Oa2R_8d2osJg
        provider:
          okta:
            issuer-uri: https://dev-02009464.okta.com/oauth2/default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s
okta:
  oauth2:
    issuer: https://dev-02009464.okta.com/oauth2/default
    audience: api://default