spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/api/v1/products/**

      - id: inventory-service
        uri: lb://inventory-service
        predicates:
        - Path=/api/v1/inventories/**

      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/v1/orders/**
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0